const get = require('../services/GET');
const errorMsg = require('../functions/returnErrorMessage');
const isInvalidLimit = require('../functions/isInvalidLimit');

async function getClientDetail(req, res) {
  const config = { headers: { Authorization: req.headers.authorization } };
  const data = await get(res, config, req.baseUrl);
  const { id } = req.params;
  const clientFiltered = data.find((client) => client.id === id);
  if (clientFiltered) {
    const policiesData = await get(res, config, '/policies');
    const policiesFiltered = policiesData.filter((policy) => policy.clientId === id);
    clientFiltered.policies = policiesFiltered;
    return clientFiltered;
  }
  errorMsg(res, 404, `No client policies were found with the clientId: ${id}`);
  return null;
}

const clientsController = {

  /**
 * Get all the clients
 * @param {object} req   Node autogenerated request object
 * @param {object} res   Node autogenerated response object
 * @returns {object}     Response with all the clients information (id, name, email, role)
 */

  async getClients(req, res) {
    const config = { headers: { Authorization: req.headers.authorization } };
    const data = await get(res, config, req.baseUrl);

    const limit = req.query.limit || 10;
    const nameFilter = req.query.name;

    let result = data;

    if (req.query.limit) {
      if (await isInvalidLimit(limit)) return errorMsg(res, 404, 'Invalid limit. It must be a number greater than 0');
    }

    if (nameFilter) {
      const filter = nameFilter.toLowerCase();
      result = data.filter((client) => ((client.name).toLowerCase()).includes(filter));
    }
    if (!result.length) {
      return errorMsg(res, 404, 'Not found any clients with that filter');
    }

    const limitedData = result.slice(0, limit);
    return res.send(limitedData);
  },

  /**
 * Get the client details.
 * @param {object} req   Node autogenerated request object
 * @param {object} res   Node autogenerated response object
 * @returns {object}     Response the client details
 *
 */

  async getClient(req, res) {
    const clientDetail = await getClientDetail(req, res);
    if (clientDetail) res.send(clientDetail);
  },

  /**
 * Get the client policies
 * @param {object} req   Node autogenerated request object
 * @param {object} res   Node autogenerated response object
 * @returns {object}     Response
 *
 */

  async getClientPolicies(req, res) {
    const clientDetail = await getClientDetail(req, res);
    if (clientDetail) {
      const clientPolicies = clientDetail.policies;
      res.send(clientPolicies);
    }
  },
};

module.exports = clientsController;
