/**
 * Sets the error code for the response and sends the error message
 * @param {object} res            Node autogenerated response object
 * @param {int} errorCode         HTTP Error Code
 * @param {int} messageReceived   Message to send
 * @returns {object}              Error Messaje
 */

module.exports = async function returnErrorMessage(res, errorCode, messageReceived) {
  res.status(errorCode);
  const errorMessage = {
    code: errorCode,
    message: messageReceived,
  };
  return res.send(errorMessage);
};
